function initDashboard(){
const IMPORTED_ROWS_KEY='scheduleImportedRows',SAFETY_BADGES_KEY='scheduleSafetyBadges',SAFETY_XLSX_URL='https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js',LIVE_REFRESH_MS=60000;
let importedRows=readImportedRows(),liveRows=Array.isArray(data)?data.slice():[],sharedSafetyBadges=null;
let safetyXlsxPromise;
const byId=id=>document.getElementById(id);
function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));}
function timeValue(value){const match=String(value||'').match(/T(\d{2}):(\d{2})/);return match?match[1]+':'+match[2]:String(value||'');}
function dateValue(value){const parts=String(value||'').split('/');return parts.length===3?parts[2]+'-'+parts[1].padStart(2,'0')+'-'+parts[0].padStart(2,'0'):String(value||'').slice(0,10);}
function shiftDateLabel(value){const date=new Date(dateValue(value)+'T00:00');return Number.isNaN(date.getTime())?String(value||''):date.toLocaleDateString('en-GB',{weekday:'short',day:'numeric',month:'short',year:'numeric'});}
function todayValue(){const now=new Date();return now.getFullYear()+'-'+String(now.getMonth()+1).padStart(2,'0')+'-'+String(now.getDate()).padStart(2,'0');}
function periodValue(value){const match=String(value||'').match(/T(\d{2}):/),hour=match?Number(match[1]):0;return hour>=5&&hour<12?'AM':hour>=12&&hour<18?'PM':'Nights';}
function cleanDateTime(value){const match=String(value||'').match(/(\d{4}-\d{2}-\d{2}T\d{2}:\d{2})/);return match?match[1]:String(value||'').trim();}
function normaliseRows(rows){if(!Array.isArray(rows))throw Error('Schedule data is not a list of shifts.');return rows.filter(row=>row&&typeof row==='object').map(row=>{const location=String(row.location||'').trim(),start=cleanDateTime(row.start);return {name:String(row.name||'').trim(),location,type:String(row.type||'')||(location.toLowerCase().includes('service provider')?'CDC':'DC'),date:String(row.date||'').trim(),start,end:cleanDateTime(row.end),hours:Number(row.hours)||0,role:String(row.role||'').trim(),period:String(row.period||'')||periodValue(start)};});}
function shiftIdentity(row){return [String(row.name||'').trim().toLowerCase(),dateValue(row.date)].join('||');}
function datesIn(rows){return new Set(rows.map(row=>dateValue(row.date)).filter(Boolean));}
function mergeRows(...sets){const rows=new Map();sets.flat().forEach(row=>{if(row.name&&row.date)rows.set(shiftIdentity(row),row);});return [...rows.values()];}
function replaceImportedDates(existing,incoming){const dates=datesIn(incoming);return mergeRows(existing.filter(row=>!dates.has(dateValue(row.date))),incoming);}
function mergedSchedule(){const dates=datesIn(importedRows);return mergeRows(liveRows.filter(row=>!dates.has(dateValue(row.date))),importedRows);}
function readImportedRows(){try{const stored=localStorage.getItem(IMPORTED_ROWS_KEY);return stored?normaliseRows(JSON.parse(stored)):[];}catch(error){console.error('Unable to read imported schedules',error);return [];}}
function saveImportedRows(rows){try{localStorage.setItem(IMPORTED_ROWS_KEY,JSON.stringify(rows));}catch(error){throw Error('Imported schedules could not be saved in this browser. Clear older imported schedules and try again.');}}
function showError(message){const error=byId('error');error.textContent=message||'';error.hidden=!message;}
function sharedBackendApiBase(){return Auth.getApiBase();}
function handleAuthFailure(error){if(error&&(error.status===401||error.status===403)){if(typeof window.onAuthExpired==='function')window.onAuthExpired('Your session is no longer valid. Please sign in again.');return true;}return false;}
function updateAdminVisibility(){const authed=Auth.isAdmin(),uploadPanel=byId('upload')&&byId('upload').closest('.panel');if(uploadPanel)uploadPanel.hidden=!authed;}
async function backendAdminRequest(url,options){const settings=options||{},token=Auth.accountToken();if(!token)throw Error('Sign in with an admin account before publishing.');const headers={Accept:'application/json',Authorization:'Bearer '+token};if(settings.body)headers['Content-Type']='application/json';let response;try{response=await fetch(url,{method:settings.method||'GET',headers,body:settings.body?JSON.stringify(settings.body):undefined});}catch(error){throw Error('The schedule backend could not be reached from this browser. Confirm the API base URL, network access, and CORS settings, then try again.');}if(!response.ok){if(response.status===401||response.status===403){if(typeof window.onAuthExpired==='function')window.onAuthExpired('Your session is no longer valid. Please sign in again.');throw Error('The backend did not accept the current session. Sign in again and retry.');}throw Error('The schedule backend rejected the request (HTTP '+response.status+').');}return response.json();}
async function publishSharedSchedule(rows){const base=sharedBackendApiBase();if(!base)return '';await backendAdminRequest(SharedSchedule.backendAdminScheduleUrl(base),{method:'PUT',body:{rows:normaliseRows(rows)}});return 'backend';}
function syncImportStatus(){const count=importedRows.length,clearButton=byId('clearImportedSchedules');byId('fileName').textContent=count?'live schedule + '+count.toLocaleString()+' imported shifts':'live schedule';if(clearButton)clearButton.disabled=!count;}
function applyMergedData(){data=mergedSchedule();setRoleOptions();syncImportStatus();renderOverview();}
function parseCsv(text){const rows=[];let row=[],cell='',quoted=false;for(let index=0;index<text.length;index++){const character=text[index],next=text[index+1];if(quoted){if(character==='"'&&next==='"'){cell+='"';index++;}else if(character==='"')quoted=false;else cell+=character;}else if(character==='"')quoted=true;else if(character===','){row.push(cell);cell='';}else if(character==='\n'){row.push(cell);rows.push(row);row=[];cell='';}else if(character!=='\r')cell+=character;}if(cell.length||row.length){row.push(cell);rows.push(row);}return rows;}
function parseUploadedCsv(text){const rows=parseCsv(text);if(!rows.length)throw Error('The file is empty.');const headers=rows[0].map(value=>String(value).replace(/^\ufeff/,'').trim().toLowerCase()),indexOf=header=>headers.indexOf(header),columns={name:indexOf('shift employee name'),location:indexOf('shift employee home location name'),date:indexOf('shift date'),start:indexOf('scheduled start time'),end:indexOf('scheduled end date'),hours:indexOf('scheduled hours'),role:headers.includes('workrole')?indexOf('workrole'):indexOf('work role')};if(Object.values(columns).some(index=>index<0))throw Error('Missing an expected schedule export column.');return rows.slice(1).filter(row=>row.some(value=>String(value).trim())).map(row=>{const location=String(row[columns.location]||'').trim(),start=cleanDateTime(row[columns.start]);return {name:String(row[columns.name]||'').trim(),location,type:location.toLowerCase().includes('service provider')?'CDC':'DC',date:String(row[columns.date]||'').trim(),start,end:cleanDateTime(row[columns.end]),hours:Number(String(row[columns.hours]||'').replace(',','.'))||0,role:String(row[columns.role]||'').trim(),period:periodValue(start)};}).filter(row=>row.name&&row.date);}
function readScheduleFile(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=event=>{try{resolve(parseUploadedCsv(event.target.result));}catch(error){reject(error);}};reader.onerror=()=>reject(Error('The browser could not read '+file.name+'.'));reader.readAsText(file);});}
async function importScheduleFiles(files){const selected=[...files].filter(file=>file&&file.name);if(!selected.length)return;let savedLocally=false;try{const imported=(await Promise.all(selected.map(readScheduleFile))).flat();if(!imported.length)throw Error('The selected files contain no shifts.');const nextImported=replaceImportedDates(importedRows,imported);saveImportedRows(nextImported);importedRows=nextImported;showError('');applyMergedData();savedLocally=true;const published=await publishSharedSchedule(mergedSchedule());byId('status').textContent=selected.length+' schedule file'+(selected.length===1?'':'s')+' merged. '+importedRows.length.toLocaleString()+' imported shifts available.'+(published?' Shared schedule published to the '+published+'.':'');}catch(error){showError((savedLocally?'The schedule was saved locally, but shared publishing failed: ':'Upload error: ')+error.message);byId('status').textContent=savedLocally?'Using the locally saved schedule.':'The current schedule is still loaded.';}}
function localDateKey(date){return date.getFullYear()+'-'+String(date.getMonth()+1).padStart(2,'0')+'-'+String(date.getDate()).padStart(2,'0');}
function selectedWeek(anchor){const date=new Date(anchor+'T00:00'),start=new Date(date);start.setDate(date.getDate()-date.getDay());const end=new Date(start);end.setDate(start.getDate()+6);return {start:localDateKey(start),end:localDateKey(end)};}
function dateInView(rowDate,anchor,view){if(!anchor)return true;if(view==='day'||!view)return rowDate===anchor;if(view==='month')return rowDate.slice(0,7)===anchor.slice(0,7);const week=selectedWeek(anchor);return rowDate>=week.start&&rowDate<=week.end;}
function reportDay(row){const date=new Date(dateValue(row.date)+'T00:00'),weekday=date.toLocaleDateString('en-GB',{weekday:'short'}),period=row.period||periodValue(row.start);return weekday+' '+period;}
function csvCell(value){return '"'+String(value??'').replace(/"/g,'""')+'"';}
function syncWeeklyReportAction(){const button=byId('downloadWeeklyReport');if(button)button.disabled=!byId('date').value;}
function missingReportDates(rows,week){const dates=new Set(rows.map(row=>dateValue(row.date))),missing=[],start=new Date(week.start+'T00:00');for(let offset=0;offset<7;offset++){const date=new Date(start);date.setDate(start.getDate()+offset);const key=localDateKey(date);if(!dates.has(key))missing.push(date.toLocaleDateString('en-GB',{weekday:'short',day:'numeric',month:'short'}));}return missing;}
function reportDateTime(date){return localDateKey(date)+'T'+String(date.getHours()).padStart(2,'0')+':'+String(date.getMinutes()).padStart(2,'0');}
function reportPeriod(date){const hour=date.getHours();return hour>=6&&hour<14?'AM':hour>=14&&hour<22?'PM':'Nights';}
function nextReportBoundary(date){const boundary=new Date(date),hour=boundary.getHours();if(hour<6)boundary.setHours(6,0,0,0);else if(hour<14)boundary.setHours(14,0,0,0);else if(hour<22)boundary.setHours(22,0,0,0);else{boundary.setDate(boundary.getDate()+1);boundary.setHours(6,0,0,0);}return boundary;}
function splitDcReportRow(row){const start=new Date(row.start),end=new Date(row.end),day=new Date(dateValue(row.date)+'T00:00').getDay();if(row.type!=='DC'||day===0||day===6||Number.isNaN(start.getTime())||Number.isNaN(end.getTime())||end<=start)return [row];const segments=[];let segmentStart=start;while(segmentStart<end){const boundary=nextReportBoundary(segmentStart),segmentEnd=boundary<end?boundary:end;segments.push({...row,date:localDateKey(segmentStart),start:reportDateTime(segmentStart),end:reportDateTime(segmentEnd),period:reportPeriod(segmentStart)});segmentStart=segmentEnd;}return segments;}
function downloadWeeklyReport(){const anchor=byId('date').value,group=byId('group').value;if(!anchor){showError('Select a shift date before downloading the weekly shift report.');return;}const week=selectedWeek(anchor),sourceRows=data.filter(row=>row.name&&row.date&&(!group||row.type===group)&&dateInView(dateValue(row.date),anchor,'week')),rows=(group==='DC'?sourceRows.flatMap(splitDcReportRow):sourceRows).sort((left,right)=>String(left.name).localeCompare(String(right.name))||dateValue(left.date).localeCompare(dateValue(right.date))||String(left.start).localeCompare(String(right.start)));if(!rows.length){showError('No '+(group?group+' ':'')+'scheduled shifts are available for '+week.start+' to '+week.end+'.');return;}const csv=[['Employee Name','Core Skill','Start','End','Day'],...rows.map(row=>[row.name,row.role,timeValue(row.start),timeValue(row.end),reportDay(row)])].map(row=>row.map(csvCell).join(',')).join('\r\n')+'\r\n',link=document.createElement('a'),missingDates=missingReportDates(rows,week);link.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));link.download='weekly-shift-report-'+week.start+'-to-'+week.end+'.csv';document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(link.href),0);showError('');byId('status').textContent='Downloaded '+rows.length.toLocaleString()+' '+(group?group+' ':'')+'shift'+(rows.length===1?'':'s')+' for '+week.start+' to '+week.end+'.'+(missingDates.length?' The loaded schedule has no shifts for '+missingDates.join(', ')+'.':'');}
function syncMonthlyHoursReportAction(){const button=byId('downloadMonthlyHoursReport');if(button)button.disabled=!byId('monthlyReportMonth').value||!byId('group').value;}
function hoursByWorkRole(rows){const areas=new Map();rows.forEach(row=>{const role=String(row.role||'Work role not specified').trim()||'Work role not specified',area=areas.get(role)||{hours:0,shifts:0,people:new Set()};area.hours+=Number(row.hours)||0;area.shifts++;area.people.add(row.name);areas.set(role,area);});return [...areas.entries()].sort(([left],[right])=>left.localeCompare(right)).map(([role,area])=>({role,hours:area.hours,shifts:area.shifts,people:area.people.size}));}
function hoursReportTotal(rows){return {hours:rows.reduce((total,row)=>total+(Number(row.hours)||0),0),shifts:rows.length,people:new Set(rows.map(row=>row.name)).size};}
function weeklyHoursRows(rows,group){const headers=['Week starting','Week ending','Team','Work role','Scheduled hours','Shift count','Coworker count'],weeks=new Map();rows.forEach(row=>{const week=selectedWeek(dateValue(row.date)),entry=weeks.get(week.start)||{end:week.end,rows:[]};entry.rows.push(row);weeks.set(week.start,entry);});const blocks=[...weeks.entries()].sort(([left],[right])=>left.localeCompare(right)).map(([start,week])=>{const summaries=hoursByWorkRole(week.rows),total=hoursReportTotal(week.rows);return [headers,...summaries.map(summary=>[start,week.end,group,summary.role,Number(summary.hours.toFixed(1)),summary.shifts,summary.people]),[start,week.end,group,'Total',Number(total.hours.toFixed(1)),total.shifts,total.people]];}),rowCount=Math.max(...blocks.map(block=>block.length));return Array.from({length:rowCount},(_,rowIndex)=>blocks.flatMap((block,blockIndex)=>[...(block[rowIndex]||Array(headers.length).fill('')),...(blockIndex<blocks.length-1?['']:[])]));}
async function downloadMonthlyHoursReport(){const month=byId('monthlyReportMonth').value,group=byId('group').value;if(!month||!group){showError('Select a team and month before downloading the monthly hours report.');return;}const sourceRows=data.filter(row=>row.name&&row.date&&row.type===group&&dateValue(row.date).slice(0,7)===month);if(!sourceRows.length){showError('No '+group+' scheduled shifts are available for '+month+'.');return;}try{const summaries=hoursByWorkRole(sourceRows),total=hoursReportTotal(sourceRows),monthlyRows=[['Month','Team','Work role','Scheduled hours','Shift count','Coworker count'],...summaries.map(summary=>[month,group,summary.role,Number(summary.hours.toFixed(1)),summary.shifts,summary.people]),['',group,'Total',Number(total.hours.toFixed(1)),total.shifts,total.people]],weeklyRows=weeklyHoursRows(sourceRows,group),XLSX=await loadSafetyXlsx(),workbook=XLSX.utils.book_new();XLSX.utils.book_append_sheet(workbook,XLSX.utils.aoa_to_sheet(monthlyRows),'Monthly hours');XLSX.utils.book_append_sheet(workbook,XLSX.utils.aoa_to_sheet(weeklyRows),'Weekly hours');const bytes=XLSX.write(workbook,{bookType:'xlsx',type:'array'}),link=document.createElement('a');link.href=URL.createObjectURL(new Blob([bytes],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}));link.download='hours-by-work-role-'+group+'-'+month+'.xlsx';document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(link.href),0);showError('');byId('status').textContent='Downloaded the '+group+' monthly and weekly hours report for '+month+' across '+summaries.length+' work role'+(summaries.length===1?'':'s')+'.';}catch(error){showError('Could not generate the monthly and weekly hours report: '+error.message);}}
function baseRows(){const query=byId('search').value.trim().toLowerCase(),group=byId('group').value,date=byId('date').value,view=byId('dateView').value,roles=[...byId('role').selectedOptions].map(option=>option.value);return data.filter(row=>allowedRoles.includes(row.role)&&(!query||row.name.toLowerCase().includes(query))&&(!group||row.type===group)&&dateInView(dateValue(row.date),date,view)&&(!roles.length||roles.includes(row.role)));}
function updatePeriodOptions(){const period=byId('period'),current=period.value,rows=baseRows(),counts={AM:0,PM:0,Nights:0};rows.forEach(row=>{if(counts[row.period]!==undefined)counts[row.period]++;});period.innerHTML='<option value="">All shift patterns ('+rows.length+')</option>'+['AM','PM','Nights'].map(value=>'<option value="'+value+'">'+value+' ('+counts[value]+')</option>').join('');period.value=['','AM','PM','Nights'].includes(current)?current:'';}
function currentFilters(){const labels=[],roles=[...byId('role').selectedOptions].map(option=>option.value),view=byId('dateView').value;if(byId('search').value.trim())labels.push('name search');if(byId('group').value)labels.push(byId('group').value);if(roles.length)labels.push(roles.length===1?roles[0]:roles.length+' roles');if(byId('period').value)labels.push(byId('period').value);if(byId('date').value)labels.push(view?view+' of '+byId('date').value:byId('date').value);return labels;}
function renderedSafetyBadgeData(){return sharedSafetyBadges||safetyBadgeData();}
function safetyBadgesFor(name){const badges=renderedSafetyBadgeData();if(!badges)return '';try{return SharedSchedule.safetyBadgesFor(badges,name).map(badge=>'<span class="badge badge-'+badge.className+'" role="img" aria-label="'+badge.label+'" title="'+badge.label+'">'+badge.symbol+'</span>').join('');}catch(error){console.error('Unable to render safety badges',error);return '';}}
function overviewCard(row){const color=roleColors[row.role]||'default',key=encodeURIComponent([row.name,row.date,row.start,row.end,row.role].join('||')),name=escapeHtml(row.name),date=dateValue(row.date),dateLabel=escapeHtml(shiftDateLabel(row.date)),badges=safetyBadgesFor(row.name);return '<li><article class="card card-'+color+'"><div class="name-row"><div class="name">'+name+'</div>'+(badges?'<div class="badges" aria-label="Safety qualifications">'+badges+'</div>':'')+'<button class="remove-btn" type="button" data-remove="'+key+'" aria-label="Remove '+name+' from this shift">Remove</button></div><div class="role role-'+color+'">'+escapeHtml(row.role||'Work role not specified')+'</div><div class="times"><div class="time"><small>Start</small><b>'+timeValue(row.start)+'</b></div><div class="time"><small>End</small><b>'+timeValue(row.end)+'</b></div></div><div class="meta"><span>'+escapeHtml(row.period)+'</span><span>'+escapeHtml(row.hours)+' hrs</span></div><div class="shift-date"><span>Shift date</span><time datetime="'+escapeHtml(date)+'">'+dateLabel+'</time></div></article></li>';}
function renderOverview(){updatePeriodOptions();if(typeof updateAbsenceSummary==='function')updateAbsenceSummary();const period=byId('period').value,rows=baseRows().filter(row=>!period||row.period===period).filter(row=>!removed[[row.name,row.date,row.start,row.end,row.role].join('||')]),people=new Set(rows.map(row=>row.name)),hours=rows.reduce((total,row)=>total+(Number(row.hours)||0),0),labels=currentFilters();byId('kpis').innerHTML=[['People',people.size,'indigo'],['Shift count',rows.length,'sky'],['Total hours',hours.toFixed(1),'green'],['Shift period',period||'All','violet']].map(item=>'<div class="kpi"><div class="label">'+item[0]+'</div><div class="value '+item[2]+'">'+item[1]+'</div></div>').join('');byId('count').textContent=rows.length.toLocaleString()+' shift'+(rows.length===1?'':'s');byId('cards').innerHTML=rows.slice().sort((left,right)=>String(left.start).localeCompare(String(right.start))).map(overviewCard).join('');byId('empty').hidden=Boolean(rows.length);byId('filterSummary').textContent=rows.length.toLocaleString()+' shift'+(rows.length===1?'':'s')+' for '+(labels.length?labels.join(', '):'all teams, roles, periods, and dates')+'.';byId('clear').disabled=!labels.length;syncWeeklyReportAction();}
function clearFilters(){byId('search').value='';byId('group').value='';byId('period').value='';byId('date').value='';byId('dateView').value='';[...byId('role').options].forEach(option=>option.selected=false);renderOverview();byId('search').focus();}
function normaliseSafetyText(value){return String(value??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().replace(/\s+/g,' ').toLowerCase();}
function safetyBadgeData(){try{const stored=localStorage.getItem(SAFETY_BADGES_KEY),data=stored?JSON.parse(stored):null;return data?SharedSchedule.normaliseSafetyBadges(data):null;}catch(error){console.error('Unable to read safety badges',error);return null;}}
function safetyNamesFromSheet(workbook,sheetName){const rows=XLSX.utils.sheet_to_json(workbook.Sheets[sheetName],{header:1,defval:''}),headerIndex=rows.findIndex(row=>row.some(cell=>normaliseSafetyText(cell)==='name'));if(headerIndex<0)return [];const nameColumns=rows[headerIndex].map((cell,index)=>normaliseSafetyText(cell)==='name'?index:-1).filter(index=>index>=0),names=new Set();rows.slice(headerIndex+1).forEach(row=>nameColumns.forEach(column=>{const name=String(row[column]??'').trim();if(name&&!normaliseSafetyText(name).startsWith('date reviewed'))names.add(name);}));return [...names];}
function safetySheets(workbook,pattern){return workbook.SheetNames.filter(name=>pattern.test(name));}
function loadSafetyXlsx(){if(window.XLSX)return Promise.resolve(window.XLSX);if(!safetyXlsxPromise)safetyXlsxPromise=new Promise((resolve,reject)=>{const script=document.createElement('script');script.src=SAFETY_XLSX_URL;script.async=true;script.onload=()=>window.XLSX?resolve(window.XLSX):reject(Error('The spreadsheet reader did not load correctly.'));script.onerror=()=>reject(Error('The spreadsheet reader could not be loaded. Check your network connection and try again.'));document.head.append(script);});return safetyXlsxPromise;}
async function parseSafetyWorkbook(file){await loadSafetyXlsx();const workbook=XLSX.read(await file.arrayBuffer(),{type:'array'}),firstAidSheets=safetySheets(workbook,/first\s*aid/i),fireSheets=safetySheets(workbook,/fire\s*marshal/i),heightSheets=safetySheets(workbook,/\bwah\b|working\s*at\s*height/i);if(!firstAidSheets.length||!fireSheets.length||!heightSheets.length)throw Error('The workbook must include First Aid, Fire Marshals, and WAH sheets.');const names=sheets=>[...new Set(sheets.flatMap(sheet=>safetyNamesFromSheet(workbook,sheet)))];return {firstAid:names(firstAidSheets),fireMarshal:names(fireSheets),workingAtHeight:names(heightSheets)};}
function syncSafetyImportStatus(){const status=byId('safetyBadgeStatus'),clearButton=byId('clearSafetyBadges'),badges=safetyBadgeData();if(!status)return;const total=badges?badges.firstAid.length+badges.fireMarshal.length+badges.workingAtHeight.length:0;status.textContent=badges?'Safety badges: '+badges.firstAid.length+' first aid, '+badges.fireMarshal.length+' fire marshal, '+badges.workingAtHeight.length+' working at height.':'No safety badge list loaded.';if(clearButton)clearButton.disabled=!total;}
async function publishSafetyBadges(badges){const base=sharedBackendApiBase();if(!base)return '';await backendAdminRequest(SharedSchedule.backendAdminSafetyBadgesUrl(base),{method:'PUT',body:{badges:SharedSchedule.normaliseSafetyBadges(badges)}});return 'shared backend';}
async function importSafetyWorkbook(file){if(!file)return;let savedLocally=false;try{const badges=SharedSchedule.normaliseSafetyBadges(await parseSafetyWorkbook(file));localStorage.setItem(SAFETY_BADGES_KEY,JSON.stringify(badges));sharedSafetyBadges=null;savedLocally=true;showError('');syncSafetyImportStatus();renderOverview();const published=await publishSafetyBadges(badges);if(published)sharedSafetyBadges=badges;renderOverview();byId('status').textContent='Safety badges imported from '+file.name+(published?' and published to the shared backend.':'.');}catch(error){showError((savedLocally?'Safety badges were saved locally, but shared publishing failed: ':'Safety upload error: ')+error.message);if(savedLocally){sharedSafetyBadges=null;syncSafetyImportStatus();renderOverview();byId('status').textContent='Using locally saved safety badges.';}}}
async function clearSafetyBadges(){const signedIn=Boolean(sharedBackendApiBase()&&Auth.accountToken());if(!confirm('Clear all imported safety badges from this browser'+(signedIn?' and the signed-in shared backend':'')+'?'))return;const hadLocalBadges=Boolean(safetyBadgeData());localStorage.removeItem(SAFETY_BADGES_KEY);sharedSafetyBadges=null;syncSafetyImportStatus();renderOverview();if(!signedIn){showError('');byId('status').textContent='Safety badges cleared locally.';return;}try{await publishSafetyBadges({firstAid:[],fireMarshal:[],workingAtHeight:[]});sharedSafetyBadges={firstAid:[],fireMarshal:[],workingAtHeight:[]};showError('');byId('status').textContent='Safety badges cleared locally and from the shared backend.';}catch(error){sharedSafetyBadges=null;showError('Safety badges were cleared locally, but shared clearing failed: '+error.message);byId('status').textContent=hadLocalBadges?'Safety badges are cleared locally; shared badges may still be visible on display devices.':'Shared safety badges may still be visible on display devices.';}}
function addSafetyControls(){const panel=byId('upload').closest('.panel'),heading=panel.querySelector('.panel-heading');if(!byId('safetyUpload')){const label=document.createElement('label'),input=document.createElement('input'),clearButton=document.createElement('button'),status=document.createElement('div');label.className='clear';label.htmlFor='safetyUpload';label.textContent='Upload safety badges';input.id='safetyUpload';input.className='visually-hidden';input.type='file';input.accept='.xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';clearButton.id='clearSafetyBadges';clearButton.className='clear';clearButton.type='button';clearButton.textContent='Clear safety badges';status.id='safetyBadgeStatus';status.className='data-note hint';status.setAttribute('role','status');status.setAttribute('aria-live','polite');heading.append(label,input,clearButton);panel.append(status);input.addEventListener('change',event=>{const [file]=event.target.files;importSafetyWorkbook(file);event.target.value='';});clearButton.addEventListener('click',clearSafetyBadges);}syncSafetyImportStatus();}
function addControls(){const dateField=byId('date').closest('.field'),uploadRow=byId('upload').closest('.panel').querySelector('.panel-heading'),filterHeading=byId('filters').closest('.panel').querySelector('.panel-heading');if(!byId('dateView')){const field=document.createElement('div');field.className='field';field.innerHTML='<label for="dateView">Date view</label><select id="dateView"><option value="">All scheduled dates</option><option value="day">Selected day</option><option value="week">Selected week</option><option value="month">Selected month</option></select>';dateField.insertAdjacentElement('afterend',field);}if(!byId('weeklyReportHelp')){const help=document.createElement('span');help.id='weeklyReportHelp';help.className='visually-hidden';help.textContent='Choose a shift date to download all loaded schedules for that Sunday to Saturday week. The selected team affects the report; work role, shift period, and date-view filters do not. DC reports split Monday to Friday shifts at 06:00, 14:00, and 22:00.';filterHeading.append(help);}if(!byId('downloadWeeklyReport')){const button=document.createElement('button');button.id='downloadWeeklyReport';button.className='clear';button.type='button';button.textContent='Download weekly shift report';button.disabled=true;button.title='Select a shift date to enable this report.';button.setAttribute('aria-describedby','weeklyReportHelp');filterHeading.querySelector('#clear').insertAdjacentElement('beforebegin',button);button.addEventListener('click',downloadWeeklyReport);}if(!byId('clearImportedSchedules')){const button=document.createElement('button');button.id='clearImportedSchedules';button.className='clear';button.type='button';button.textContent='Clear imported schedules';uploadRow.append(button);button.addEventListener('click',()=>{if(confirm('Clear all imported schedules from this browser?')){importedRows=[];localStorage.removeItem(IMPORTED_ROWS_KEY);applyMergedData();byId('status').textContent='Imported schedules cleared. Showing the live schedule.';}});}}
function addMonthlyHoursReportControl(){const filters=byId('filters'),filterHeading=filters.closest('.panel').querySelector('.panel-heading');if(!byId('monthlyReportMonth')){const field=document.createElement('div');field.className='field';field.innerHTML='<label for="monthlyReportMonth">Report month</label><input id="monthlyReportMonth" type="month" aria-describedby="monthlyHoursReportHelp">';filters.append(field);const help=document.createElement('span');help.id='monthlyHoursReportHelp';help.className='visually-hidden';help.textContent='Select a DC or CDC team and calendar month to download total scheduled hours by work role. Other dashboard filters do not affect this report.';filterHeading.append(help);const button=document.createElement('button');button.id='downloadMonthlyHoursReport';button.className='clear';button.type='button';button.textContent='Download monthly hours report';button.disabled=true;button.title='Select a team and month to enable this report.';button.setAttribute('aria-describedby','monthlyHoursReportHelp');filterHeading.querySelector('#clear').insertAdjacentElement('beforebegin',button);button.addEventListener('click',downloadMonthlyHoursReport);byId('monthlyReportMonth').addEventListener('input',syncMonthlyHoursReportAction);byId('group').addEventListener('input',syncMonthlyHoursReportAction);}syncMonthlyHoursReportAction();}
async function refreshSharedSafetyBadges(){const base=sharedBackendApiBase();if(!base){sharedSafetyBadges=null;return;}try{sharedSafetyBadges=await SharedSchedule.fetchBackendSafetyBadges(base,undefined,Auth.accountToken());}catch(error){sharedSafetyBadges=null;console.error('Unable to load shared safety badges',error);}}
async function refreshLiveRows(){const base=sharedBackendApiBase();if(!base){showError('No backend API base URL is configured. Sign in again to restore access.');return;}const token=Auth.accountToken();if(!token){if(typeof window.onAuthExpired==='function')window.onAuthExpired('Your session is no longer valid. Please sign in again.');return;}try{liveRows=normaliseRows(await SharedSchedule.fetchBackendSchedule(base,undefined,token));await refreshSharedSafetyBadges();showError('');applyMergedData();byId('status').textContent='Shared backend schedule updated '+new Date().toLocaleTimeString()+(importedRows.length?' with '+importedRows.length.toLocaleString()+' imported shifts.':'.');}catch(error){console.error('Unable to load shared backend schedule',error);if(handleAuthFailure(error))return;showError('Live schedule could not be refreshed. Showing the last loaded schedule.');}}
function handleUpload(event){event.stopImmediatePropagation();importScheduleFiles(event.target.files);event.target.value='';}
function handleDrop(event){event.preventDefault();event.stopImmediatePropagation();byId('drop').classList.remove('drag');importScheduleFiles(event.dataTransfer.files);}
function openStableTeamCardView(group,event){event.preventDefault();event.stopImmediatePropagation();try{const popup=window.open(SharedSchedule.cardViewUrl('card_view.html',{team:group,search:byId('search').value.trim(),roles:[...byId('role').selectedOptions].map(option=>option.value),api:sharedBackendApiBase()}),'_blank','popup');if(!popup)showError('The card view could not be opened. Allow pop-ups for this dashboard and try again.');}catch(error){showError('The shared card link could not be created: '+error.message);}}
addControls();addMonthlyHoursReportControl();addSafetyControls();updateAdminVisibility();dataSource='uploaded schedule';syncImportStatus();['search','group','period'].forEach(id=>byId(id).addEventListener('input',renderOverview));byId('date').addEventListener('input',event=>{event.stopImmediatePropagation();renderOverview();},true);byId('role').addEventListener('change',renderOverview);byId('dateView').addEventListener('change',()=>{if(byId('dateView').value&&!byId('date').value)byId('date').value=todayValue();renderOverview();});byId('clear').onclick=clearFilters;byId('emptyClear').onclick=clearFilters;byId('upload').addEventListener('change',handleUpload,true);byId('drop').addEventListener('drop',handleDrop,true);byId('dcCardView').addEventListener('click',event=>openStableTeamCardView('DC',event),true);byId('cdcCardView').addEventListener('click',event=>openStableTeamCardView('CDC',event),true);renderOverview();refreshLiveRows();setTimeout(applyMergedData,1000);setTimeout(applyMergedData,5000);setInterval(refreshLiveRows,LIVE_REFRESH_MS);setInterval(updateAdminVisibility,30000);
window.refreshSchedule=refreshLiveRows;
window.renderOverview=renderOverview;
}
window.initDashboard=initDashboard;
